css/login.css, css/main.css, include/common.php, index.php, init.php, login.php
- title top bottom add 40px
- forgot password text color code change to 8e8e8e
- button height add 50px
=> update- modify login css

changePassword.php, css/changePassword.css, css/login.css, css/main.css, forgotPassword.php, include/common.php, login.php
update- add $_SESSION['userid'] variable on login page
update- modify css file
update- modify redirect link on forgotPassword page
=> feat- add changePassword page

audit_log.php, include/common.php, init.php, login.php, logout.php, pin.php, pin_table.php
update- login page with audit log function
update- pin page with audit log function
feat- logout file
Db:
DROP TABLE IF EXISTS `audit_log`;
CREATE TABLE IF NOT EXISTS `audit_log` (
`log_action` int DEFAULT NULL,
`screen_type` varchar(255) DEFAULT NULL,
`query_record` text DEFAULT NULL,
`query_table` varchar(255) DEFAULT NULL,
`old_value` varchar(255) DEFAULT NULL,
`new_value` varchar(255) DEFAULT NULL,
`changes` varchar(255) DEFAULT NULL,
`user_id` int DEFAULT NULL,
`action_message` text,
) ENGINE=MyISAM DEFAULT CHARSET=latin1;
COMMIT;
=> feat- add audit log page

audit_log.php, css/pin.css, header.php, include/common.php, init.php, js/common.fun.js, login.php, logout.php, pin.php, pin_group.php, pin_group_table.php, pin_table.php
=> feat- add pin group page

audit_log.php, brand.php, brand_table.php, css/main.css, init.php, js/common.fun.js, marital_status.php, marital_status_table.php, platform.php, platform_table.php, prod_status.php, prod_status_table.php, warehouse.php, warehouse_table.php
db:
DROP TABLE IF EXISTS `marital_status`;
CREATE TABLE IF NOT EXISTS `marital_status` (
`name` varchar(100) DEFAULT NULL,
`remark` varchar(255) DEFAULT NULL,
`update_by` varchar(255) DEFAULT NULL,
`update_date` date DEFAULT (CURRENT_DATE),
`update_time` time DEFAULT (CURRENT_TIME),
`status` char(1) DEFAULT NULL,
) ENGINE=MyISAM AUTO_INCREMENT=1 DEFAULT CHARSET=latin1;
COMMIT;
=> feat- add marital status page

bank.php, bank_table.php, css/main.css, init.php
db:
DROP TABLE IF EXISTS `bank`;
CREATE TABLE IF NOT EXISTS `bank` (
`name` varchar(100) DEFAULT NULL,
`remark` varchar(255) DEFAULT NULL,
`update_by` varchar(255) DEFAULT NULL,
`update_date` date DEFAULT (CURRENT_DATE),
`update_time` time DEFAULT (CURRENT_TIME),
`status` char(1) DEFAULT NULL,
) ENGINE=MyISAM AUTO_INCREMENT=1 DEFAULT CHARSET=latin1;
COMMIT;
=> feat- add bank page

bank.php, bank_table.php, css/main.css, em_type_status.php, em_type_status_table.php, init.php
db:
DROP TABLE IF EXISTS `em_type_status`;
CREATE TABLE IF NOT EXISTS `em_type_status` (
`name` varchar(100) DEFAULT NULL,
`remark` varchar(255) DEFAULT NULL,
`update_by` varchar(255) DEFAULT NULL,
`update_date` date DEFAULT (CURRENT_DATE),
`update_time` time DEFAULT (CURRENT_TIME),
`status` char(1) DEFAULT NULL,
) ENGINE=MyISAM AUTO_INCREMENT=1 DEFAULT CHARSET=latin1;
COMMIT;
=> feat- add employment type status page

bank.php, bank_table.php, css/form.css, css/main.css, currencies.php, currencies_table.php, currency_unit.php, currency_unit_table.php, em_type_status.php, em_type_status_table.php, init.php
db:
DROP TABLE IF EXISTS `currency_unit`;
CREATE TABLE IF NOT EXISTS `currency_unit` (
`unit` varchar(100) DEFAULT NULL,
`remark` varchar(255) DEFAULT NULL,
`update_date` date DEFAULT (CURRENT_DATE),
`update_time` time DEFAULT (CURRENT_TIME),
`update_by` varchar(255) DEFAULT NULL,
`status` char(1) DEFAULT NULL,
) ENGINE=MyISAM AUTO_INCREMENT=1 DEFAULT CHARSET=latin1;
COMMIT;
DROP TABLE IF EXISTS `currencies`;
CREATE TABLE IF NOT EXISTS `currencies` (
`default_currency_unit` int DEFAULT NULL,
`exchange_currency_rate` float DEFAULT NULL,
`exchange_currency_unit` int DEFAULT NULL, …
=> feat- add currency unit page and currencies page

bank.php, brand.php, currencies.php, currency_unit.php, department.php, designations.php, em_type_status.php, holiday.php, include/connection.php, marital_status.php, menu_bar.php, pin.php, pin_group.php, platform.php, prod_status.php, user_group.php, warehouse.php
update- add page into menu bar
update- add link for the sidebar button
update- redirect all the page to login when session value not detected
update- make the table scrollable of the user group page
=> update- change the action message of the audit log

css/main.css, css/pin.css, menu_bar.php, pin.php, pin_group.php, pin_group_table.php
update- fix pin/pin group page css
=> feat- sidebar will close when click outside

bank.php, brand.php, css/main.css, css/pin.css, currencies.php, currency_unit.php, department.php, designations.php, em_type_status.php, holiday.php, make_order.php, marital_status.php, menu_bar.php, pin.php, pin_group.php, pin_group_table.php, platform.php, prod_status.php, user_group.php, warehouse.php
feat- add common function to make order page
=> feat- add checking for the input after insert into db

bank.php, brand.php, changePassword.php, css/changePassword.css, css/main.css, currencies.php, currency_unit.php, department.php, designations.php, em_type_status.php, header.php, holiday.php, init.php, js/common.fun.js, make_order.php, marital_status.php, menuHeader.php, package.php, pin.php, pin_group.php, platform.php, prod_status.php, product.php, rate_checking.php, user.php, user_group.php, warehouse.php, weight_unit.php
update- button will present in column when view in mobile view
feat- add css for fixing dropmenu display inside table when view in safari
=> update- define session user_id on init file

bank.php, brand.php, css/main.css, currencies.php, currency_unit.php, department.php, designations.php, em_type_status.php, holiday.php, marital_status.php, package.php, pin.php, pin_group.php, platform.php, prod_status.php, product.php, user.php, user_group.php, warehouse.php, weight_unit.php
update- fix search overlapped by check box
update- modify double if else method
update- fix page scroll up when clicking record barcode? checkbox
=> update- fix all page run off issue

system_setting.php
added email format checking and changed input type for company contact field
=> feat - resolved bugs

allLeaveTransaction.php, js/common.fun.js, js/leaveTransaction.js, leaveTransaction.php, myLeaveTransaction.php
-Resolve edit page run off problem
-Balance Leave Credit Display Error
-Leave Transaction Validation Function Bug
-Submit Button cannot click
=> feat - resolve several bug

finance/tax.php, finance/tax_table.php, js/tax.js
update country column (autocomplete)
=> feat - resolve bugs

finance/tax.php, finance/tax_table.php
=> feat - update country table

finance/internal_consume_ticket_credit.php, finance/internal_consume_ticket_credit_table.php, menu_bar.php
=> feat - change the ticket title

finance/shopee_acc.php, finance/shopee_acc_table.php, menu_bar.php
-change currency to currency unit
-change shopee account management in menubar
=> feat - add duplicate record for acc name

finance/agent.php, js/agent.js
=> feat - add duplicate record

finance/fb_order_req.php, finance/fb_order_req_table.php, login.php
=> feat - resolved page not working

menu_bar.php
Reverts beyourdiary-global/uat.cms#376
=> Revert "Update menu_bar.php"

finance/downline_top_up_record_table.php, js/dw_top_up_record.js
=> feat - resolve brand column select to data

css/main.css, menu_bar.php, user.php
Add User to menu bar, added password field to user page
=> feat - Added Password field to User Page
